### PR TITLE
Fix Issue 123 and Update pre-delete work-flow

### LINKED ISSUE #123: Make var-usage consistent in find-collision.sh
Currently, initializing `DC` as an [empty array](https://github.com/plus3it/join-domain-formula/blob/master/join-domain/elx/openldap-client/files/find-collisions.sh#L112) (not compatible with `set -u` in BASH pre-4.4 but not the actual error)

Subsequently, use `DC` as a [standard var](https://github.com/plus3it/join-domain-formula/blob/master/join-domain/elx/openldap-client/files/find-collisions.sh#L117) rather than an array

After _that_ reference `DC` as an [array](https://github.com/plus3it/join-domain-formula/blob/master/join-domain/elx/openldap-client/files/find-collisions.sh#L126-L132), again.

Bad juju overall...

Need to make the typing-consistent so that `set -u` is happy with `DC`'s usage on line 126.

### PR DESCRIPTION
**Pull request by ferricoxide**
Closes #123 as well as includes miscellaneous cleanup and workflow enhancements

Tested/verified in dev and both prod environments:

* Pre-delete logic not necessary in dev and one of the prod environments (with the addition of the graduated-retry), but remains necessary in other prod environment
* Still some lingering unbound vars (that only get triggered in _some_ usage-scenarios) that prevent the use of [BASH strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)

### CODE REVIEW

File: join-domain/elx/openldap-client/files/find-collisions.sh [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #!/bin/bash
 # shellcheck disable=
 #
-set -euo pipefail
+# set -euo pipefail
```
Comment (lorengordon) [inline join-domain/elx/openldap-client/files/find-collisions.sh]: was this commented out as a debugging measure?

File: join-domain/elx/pbis/init.sls [hunk 2]
```diff
@@ -27,14 +27,6 @@ PBIS-NETBIOSfix:
     - require:
       - pkg: PBIS-install
 
-PBIS-KillCollision:
-  cmd.script:
-    - name: 'fix-collisions.sh "{{ join_domain.dns_name }}" "{{ join_domain.username }}" "{{ join_domain.encrypted_password }}" "{{ join_domain.key }}"'
-    - source: 'salt://{{ files }}/fix-collisions.sh'
```
Comment (lorengordon) [inline join-domain/elx/pbis/init.sls]: Might as well delete the pbis fix-collisions.sh file also

File: join-domain/elx/openldap-client/files/find-collisions.sh (hunk 1 above)
Comment (ferricoxide) [reply join-domain/elx/openldap-client/files/find-collisions.sh]: Commented out because it doesn't work when uncommented. It (the uncommented line) was originally added to try to tease out some issues relevant to this PR, but it's otherwise not currently relevant.

File: join-domain/elx/pbis/init.sls (hunk 2 above)
Comment (ferricoxide) [reply join-domain/elx/pbis/init.sls]: Didn't delete it because it's still a usable tool (for the daring)

Comment (lorengordon) [reply join-domain/elx/pbis/init.sls]: Is this project going to continue supporting it?

Comment (ferricoxide) [reply join-domain/elx/pbis/init.sls]: Nothing in these projects are "supported" outside the context of use via salt-call.
